# Nome da automação que vai aparecer na aba 'Actions' do GitHub
name: Testes de API e E2E (Newman + Cypress)

# Define QUANDO este pipeline deve ser disparado automaticamente
on:
  # Dispara sempre que houver um 'git push' para a branch develop
  push:
    branches: [ "develop" ]
  # Dispara sempre que uma 'Pull Request' for aberta ou atualizada para a branch develop
  pull_request:
    branches: [ "develop" ]

# Bloco de trabalhos (tarefas) que o GitHub Actions vai executar
jobs:
  test:
    # Especifica o sistema operacional da máquina virtual temporária fornecida pelo GitHub
    runs-on: ubuntu-latest

    # Lista de passos sequenciais que a máquina virtual vai seguir de cima para baixo
    steps:
    
    # Passo 1: Clona/baixa o código do seu repositório para dentro da máquina virtual do GitHub
    - name: Checkout do código
      uses: actions/checkout@v3

    # Passo 2: Prepara o ambiente instalando a versão 18 do Node.js
    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # Passo 3: Instala as dependências do projeto (incluindo Cypress se estiver no package.json)
    - name: Instalar dependências do projeto
      run: npm ci

    # Passo 4: Instala globalmente a biblioteca do Newman
    - name: Instalar Newman
      run: npm install -g newman

    # Passo 5: Pausa a execução por 20 segundos para dar tempo do Render concluir o deploy
    - name: Aguardar sincronização do Render Staging
      run: sleep 20

    # Passo 6: Executa os testes de API (Postman/Newman)
    - name: Executar testes Postman no Staging (Render)
      run: npx newman run tests/juice-shop.postman_collection.json -e tests/juice-shop.postman_environment.json

    # Passo 7: Executa os testes E2E do Cypress em modo headless (após o sucesso da API)
    - name: Executar testes E2E com Cypress
      uses: cypress-io/github-action@v5
      with:
        record: false