# Nome da automação que vai aparecer na aba 'Actions' do GitHub
name: Testes de API e E2E (Newman + Cypress)

# Define QUANDO este pipeline deve ser disparado automaticamente
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Passo 1: Baixa o código do repositório
    - name: Checkout do código
      uses: actions/checkout@v4

    # Passo 2: Configura o Node.js no servidor do GitHub
    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    # Passo 3: Instala o Newman para a API
    - name: Instalar Newman
      run: npm install -g newman

    # Passo 4: Instala o Cypress e as dependências do projeto
    - name: Instalar dependências e Cypress
      run: npm install

    # Passo 5: Pausa para sincronização do Render Staging
    - name: Aguardar sincronização do Render Staging
      run: sleep 20

    # Passo 6: Executa os testes de API com o Newman
    - name: Executar testes Postman no Staging (Render)
      run: npx newman run tests/juice-shop.postman_collection.json -e tests/juice-shop.postman_environment.json

    # Passo 7: Executa os testes do Cypress
    - name: Executar testes E2E com Cypress
      run: npx cypress run